### ISSUE TITLE
can not work properly on mobile[Chrome/Tencent]

### ISSUE THREAD

**Issue by laikee99** [walkor/workerman-webrtc#2]
as title mentioned, many probs show on mobi,
In chrome, when both side connected, the video just black , remoteVideo's stream is null,
in qq, it can not even sent msg to websockets.
Need help, thanks

**Comment by walkor** [comment]
Not all browsers support webrtc, and web RTC compatibility between browsers is not good enough. Don't expect webrtc to work in all browsers.

**Comment by laikee99** [comment]
Almost forget this issue.
Thank you for what you have achieved. :)
